spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      poolName: EmployeeManagementDBPool
  jpa:
    properties:
      hibernate:
        show_sql : true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_ddl: false

  